### ISSUE TITLE
Allow injection of MARC::Record-compatible class to readers?

### ISSUE THREAD

**Issue by billdueber** [ruby-marc/ruby-marc#33]
I've seen a few project now where people monkey-patch MARC::Record to get local functionality (e.g., `record.oclcs`. This would be made unnecessary if the options passed to the Reader initializers would take an optional `:record_class => MARC::Record`. 

One can, of course, `extend` each individual record as it's created, but that's feels dirtier to me.

The change should be easy-ish and is obviously backward compatible if the default is made MARC::Record. I'm happy to do the work if folks aren't against it.

I imagine most of the time it would look like this:

``` ruby

class MyMARCRecord < MARC::Record
  def isbn
    self['020'] and self['020']['a'] and StdNums::ISBN.normalize(self['020']['a'] 
  end
end

reader = MARC::Reader.new(filename, :record_class => MyMARCRecord)

```

...or perhaps even better:

``` ruby

class MyMARCRecord < MARC::Record
  include MARC::Record::UMichExtensions
  include MARC::Record::TrajectExtensions
end

reader = MARC::Reader.new(filename, :record_class => MyMARCRecord)

```

Any thoughts?

**Comment by adjam** [comment]
This appears to be closeable as well.
