### ISSUE TITLE
Release current code as 1.0 after the winter break

### ISSUE THREAD

**Issue by billdueber** [ruby-marc/ruby-marc#39]
I'd like to release the current code base (0.8.2) as version 1.0.0 early in the new year, with the idea that we should have a 1.0 before investigating breaking changes to a gem that so many people rely on. 

Despite all our fervent hopes, MARC21 isn't going away anytime soon, so we (meaning "me", and anyone else who wants in) might as well take out some of the pain points of the current library. Some of the stuff that has been tacked on over the years (e.g., marc-in-json, the character conversion stuff) could be better integrated, the code in general needs a once-over, and the state of XML generation needs some serious love if it's going to have an acceptable speed. 

The latter would be a potentially breaking change, if there are people out there who count on REXML objects being passed around. 

Other stuff we've talked about --- some dependency injection, for example, and maybe a better way to manage readers/writers -- would go into a 2.0 release.

Thoughts? And does anyone else care about this stuff besides me?

**Comment by billdueber** [comment]
@rsinger @jrochkind @edsu @daniels OK, so I'm going to pull the trigger and release the current code as 1.0, with suitable announcement to code4lib mailing list, unless folks object. Any thoughts?

**Comment by jrochkind** [comment]
sounds good!

**Comment by rsinger** [comment]
:+1:

**Comment by daniels** [comment]
Great!

**Comment by edsu** [comment]
Yay!

**Comment by jrochkind** [comment]
Is it current master that you released, or a snapshot of the last release re-released as 1.0?  Master had evoled since the last release. If the latter, can we do a 1.1 with master as it is now, pre backwards incompatibility or major bug-risking changes that may come soon?
