### ISSUE TITLE
Add a field to record and save the change

### ISSUE THREAD

**Issue by AdeIa** [ruby-marc/ruby-marc#44]
Hi,

I use your gem for my application and I have a question. Is it possible to edit the xml file which was read with MARC::XMLReader? I need to add a new field into records in the xml file.

I see there is the append method for adding a field and subfields to the record. I need to save this add to the xml file from which the record was read. Is there any way to do it please?

**Comment by jrochkind** [comment]
You could edit the XML using just plain XML tools, without having to use ruby-marc at all. For instance, Nokogiri. Read the XML in, modify it, and write it back out again. 

But you could also do that with ruby-marc sure. Read the Marc in, modify it, write it back out to an XML file.  If the record comes in the middle of a file with lots of other records -- you've got to write the whole file back out, with all the records, some you've made changes to and some you haven't. That will be true with the Nokogiri solution too. 

There is no special functionality for editing a file 'in place' or anything, but you can read it in to an array of MARC::Record's, change some or all of the records, and then write them all out again to a file. If you write them out again to the same file location as you read from, you'll overwrite it with a new version. 

Hope this helps!

**Comment by AdeIa** [comment]
Yes, thank you for your advice!
