### ISSUE TITLE
In ruby 2.5, MARC::XMLReader with `rexml` can cause crash with core dump

### ISSUE THREAD

**Issue by jrochkind** [ruby-marc/ruby-marc#53]
I think this is probably a bug in MRI 2.5 Rexml itself, but reporting it here as I try to narrow it down. Ran into this in a test on traject, reproduced on both travis and my local macbook. Narrowed down to this test case:

```ruby
sample_xml = <<EOF
<record>
  <leader>01092pam a2200289 a 4500</leader>
</record>
EOF

MARC::XMLReader.new(StringIO.new(sample_xml), parser: 'rexml').first
```

For me causes a core dump with `/Users/jrochkind/.gem/ruby/2.5.0/gems/marc-1.0.2/lib/marc/xml_parsers.rb:179: [BUG] Stack consistency error (sp: 187, bp: -563127808)`

Trying to narrow down into a test case using only REXML to report on ruby bug tracker. 

But if anyone wants to confirm they can reproduce this, it would be helpful.

**Comment by jrochkind** [comment]
Reported to ruby bug tracker, with repro not involving ruby-marc. 

https://bugs.ruby-lang.org/issues/14403

**Comment by adjam** [comment]
@jrochkind seems like the ultimate cause is a [bug in MRI 2.5.0](https://bugs.ruby-lang.org/issues/14273) which, on my reading, is severe enough that nobody should be using that release.  Recommending we close this.

**Comment by jrochkind** [comment]
Thanks for following up, closing.
