### ISSUE TITLE
Nokogiri parser can fail silently

### ISSUE THREAD

**Issue by adjam** [ruby-marc/ruby-marc#55]
Related to /traject/traject#127

The `MARC::NokogiriReader` class does not override `#error(String)` from its parent class, which appears to be a no-op: https://github.com/sparklemotion/nokogiri/blob/master/lib/nokogiri/xml/sax/document.rb#L153

It should be as simple as adding 

```ruby 
def error(msg)
    raise(StandardError, "Error reading XML document: #{msg}")
end
```
to the `MARC::NokogiriReader` class.

Unfortunately it looks like the Nokogiri infrastructure doesn't provide location information, but at least there's an error message.

**Comment by jrochkind** [comment]
Would this change be a backwards incompat, do you think? Or shall we consider it a bugfix? Either way, should it be configurable in case someone wants the old behavior?

Just asking questions, I'm not sure. 

I'm not sure who if anyone is really stewarding ruby-marc these days. @adjam , are you interested in commit/release privs?

**Comment by adjam** [comment]
It is a change in behavior,but if you don't like silent failures, a good one  I came across this due to 125K records missing in traject output.  

I briefly considered trying to make it a configuration option, but I believe it's very important to just terminate processing on bad XML. Also, it matches the REXML parser behavior.

It also doesn't override `warning` which one might also want.
